#!/bin/bash
set -e

# Multi-node cluster mode: delegate to scripts/multi-node-docker/
for arg in "$@"; do
    case "$arg" in
        --nodes|--nodes=*)
            exec "$(dirname "$0")/scripts/multi-node-docker/start-cluster.sh" "$@"
            ;;
    esac
done

# Single-node mode — choose storage backend as first positional arg.
# Usage:
#   ./cyoda-go-docker.sh postgres    # default — postgres in docker
BACKEND="${1:-postgres}"
shift || true

case "$BACKEND" in
    postgres) ;;
    -*|--*)
        # First arg looks like a flag — treat it as a docker compose flag, default backend to postgres
        set -- "$BACKEND" "$@"
        BACKEND="postgres"
        ;;
    *)
        echo "error: unknown backend '$BACKEND' — use 'postgres'" >&2
        exit 1
        ;;
esac

echo "Starting cyoda-go with backend: $BACKEND"

# Generate a fresh JWT signing key, base64-encode for single-line .env compatibility
JWT_KEY_B64="$(openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 2>/dev/null | base64 | tr -d '\n')"

# Common env prelude — written to .env.docker for all backends.
cat > .env.docker <<EOF
# Auto-generated by cyoda-go-docker.sh — do not edit manually
# Backend: $BACKEND

# Server
CYODA_HTTP_PORT=8123
CYODA_GRPC_PORT=9123
CYODA_LOG_LEVEL=info

EOF

cat >> .env.docker <<EOF
# Storage: postgres
CYODA_STORAGE_BACKEND=postgres
CYODA_POSTGRES_URL=postgres://minicyoda:minicyoda@postgres:5432/minicyoda?sslmode=disable
CYODA_POSTGRES_AUTO_MIGRATE=true

EOF

cat >> .env.docker <<EOF
# JWT auth (key is base64-encoded PEM, decoded by the app)
CYODA_IAM_MODE=jwt
CYODA_JWT_SIGNING_KEY=${JWT_KEY_B64}
CYODA_BOOTSTRAP_CLIENT_ID=m2m.user
CYODA_BOOTSTRAP_CLIENT_SECRET=78f647e3309c4c5e0d4dddcbabc9c613ba9bfd9bc5e442d912d630cdc66fe087
CYODA_BOOTSTRAP_TENANT_ID=riskblocs
CYODA_BOOTSTRAP_ROLES=ROLE_ADMIN,ROLE_M2M

# Observability
CYODA_OTEL_ENABLED=true
OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-backend:4318
EOF

echo "Generated .env.docker (backend=$BACKEND, fresh JWT signing key)"

# Export ports for docker-compose.yml port mapping
export CYODA_HTTP_PORT=8123
export CYODA_GRPC_PORT=9123

# Compose profile selects the postgres container; otel-backend and
# cyoda-go services are always started.
export COMPOSE_PROFILES="$BACKEND"

docker compose --profile "$BACKEND" up --build "$@"
