-- Re-enable FORCE ROW LEVEL SECURITY on all tables.
ALTER TABLE entities FORCE ROW LEVEL SECURITY;
ALTER TABLE entity_versions FORCE ROW LEVEL SECURITY;
ALTER TABLE sm_audit_events FORCE ROW LEVEL SECURITY;
ALTER TABLE models FORCE ROW LEVEL SECURITY;
ALTER TABLE kv_store FORCE ROW LEVEL SECURITY;
ALTER TABLE messages FORCE ROW LEVEL SECURITY;
