// Package parity — schema_extension_property.go
//
// Property-based B-I1 assertion: for each of 50 seeded extension
// sequences, the HTTP fold bytes equal an in-memory oracle's output
// for the same seed. Divergence between oracle and backend — in either
// direction — surfaces as a test failure. Skipped under -short.
package parity

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strconv"
	"testing"

	"github.com/cyoda-platform/cyoda-go/e2e/parity/client"
	"github.com/cyoda-platform/cyoda-go/internal/domain/model/schema/gentree"
)

// propertyNumSeeds is the number of seeded sequences driven per backend.
// 50 × 3 backends × extensionsPerSeed entity creates stays inside the
// per-scenario CI budget enforced by Task 28.
const propertyNumSeeds = 50

// extensionsPerSeed is the total number of values generated per seed
// (including the initial schema-seed body). Oracle + backend attempt
// each in order; both independently decide accept/reject.
const extensionsPerSeed = 8

// gentreeDepth and gentreeWidth bound the generated tree. Kept small
// enough that 50 × 8 Walk+Extend folds per backend complete in-budget.
const gentreeDepth = 3
const gentreeWidth = 4

// RunSchemaExtensionByteIdentityProperty drives 50 seeded extension
// sequences through the fixture backend and asserts the fold bytes
// equal the in-memory oracle's output for the same seed. Oracle and
// backend converge on which extensions are accepted: shape-incompatible
// extensions are rejected identically by both (via schema.Extend in
// the oracle, via CreateEntity HTTP rejection in the backend). If they
// agree on acceptance, the final fold bytes match; divergence surfaces
// as a test failure with a seed + diff reproducer.
func RunSchemaExtensionByteIdentityProperty(t *testing.T, fixture BackendFixture) {
	if testing.Short() {
		t.Skip("property-based parity tests require full mode (drop -short)")
	}
	for seed := int64(1); seed <= propertyNumSeeds; seed++ {
		seed := seed
		t.Run(fmt.Sprintf("seed_%02d", seed), func(t *testing.T) {
			runPropertySeed(t, fixture, seed)
		})
	}
}

// runPropertySeed generates extensionsPerSeed object-typed extensions
// deterministically from seed, drives them through the HTTP stack, and
// compares the exported SIMPLE_VIEW bytes to the oracle's output.
func runPropertySeed(t *testing.T, fixture BackendFixture, seed int64) {
	cfg := gentree.DefaultConfig()
	cfg.Seed = seed
	rng := gentree.NewRNG(seed)

	// Force each top-level extension to be an object so ImportModel +
	// CreateEntity receive a JSON object (those endpoints reject
	// non-objects at the HTTP layer, which is not the property we're
	// testing). The per-field VALUES are still freely generated by
	// gentree.GenValue, which exercises leaves, nested objects, and
	// arrays under the fold.
	extensions := make([]any, extensionsPerSeed)
	for i := range extensions {
		// Width between 1 and gentreeWidth fields per object.
		n := 1 + rng.IntN(gentreeWidth)
		obj := make(map[string]any, n)
		for j := 0; j < n; j++ {
			key := "f" + strconv.Itoa(j)
			obj[key] = gentree.GenValue(rng, gentreeDepth, gentreeWidth, cfg)
		}
		extensions[i] = obj
	}

	// Oracle fold: accept the extensions the in-memory pipeline accepts,
	// record which indices those were.
	expected, oracleAccepted, err := expectedSimpleViewFromExtensions(extensions, "LOCKED")
	if err != nil {
		t.Fatalf("oracle: %v", err)
	}
	if expected == nil {
		t.Fatalf("oracle produced nil bytes — seed %d generated no acceptable extensions", seed)
	}

	tenant := fixture.NewTenant(t)
	c := client.NewClient(fixture.BaseURL(), tenant.Token)

	modelName := fmt.Sprintf("b-i1-property-seed-%d", seed)
	const modelVersion = 1

	// Oracle always accepts index 0 (seeds the schema). The HTTP stack's
	// equivalent is ImportModel with extension 0; any failure here is a
	// hard error (there's nothing to compare against).
	seedRaw, err := json.Marshal(extensions[oracleAccepted[0]])
	if err != nil {
		t.Fatalf("marshal seed body: %v", err)
	}
	if err := c.ImportModel(t, modelName, modelVersion, string(seedRaw)); err != nil {
		t.Fatalf("ImportModel seed (seed=%d): %v\nseed body: %s", seed, err, string(seedRaw))
	}
	if err := c.LockModel(t, modelName, modelVersion); err != nil {
		t.Fatalf("LockModel (seed=%d): %v", seed, err)
	}
	if err := c.SetChangeLevel(t, modelName, modelVersion, "STRUCTURAL"); err != nil {
		t.Fatalf("SetChangeLevel STRUCTURAL (seed=%d): %v", seed, err)
	}

	// Drive extensions[1..] through CreateEntity. Track which the backend
	// accepted so divergence from the oracle produces a useful diff.
	backendAccepted := []int{oracleAccepted[0]}
	for i := 1; i < len(extensions); i++ {
		raw, err := json.Marshal(extensions[i])
		if err != nil {
			t.Fatalf("marshal extension %d: %v", i, err)
		}
		if _, err := c.CreateEntity(t, modelName, modelVersion, string(raw)); err != nil {
			// Backend rejected — log for debuggability but do not fail.
			// If the oracle also rejected this index, fold bytes still
			// match. Divergence surfaces only at the final byte compare.
			t.Logf("seed=%d extension %d: backend rejected: %v", seed, i, err)
			continue
		}
		backendAccepted = append(backendAccepted, i)
	}

	got, err := c.ExportModel(t, "SIMPLE_VIEW", modelName, modelVersion)
	if err != nil {
		// Surface oracle state so the failure is diagnosable even when
		// the backend itself returned an error (e.g. the sqlite-specific
		// MODEL_NOT_FOUND storm after a 500 SERVER_ERROR during
		// validateOrExtend — see task 27 reporting).
		extBytes, _ := json.MarshalIndent(extensions, "", "  ")
		t.Fatalf(
			"ExportModel failed\n"+
				"  fixture:         %s\n"+
				"  seed:            %d\n"+
				"  err:             %v\n"+
				"  oracle accepted: %v\n"+
				"  backend accepted:%v\n"+
				"  oracle bytes:    %s\n"+
				"  extensions:\n%s",
			t.Name(), seed, err, oracleAccepted, backendAccepted,
			string(expected), string(extBytes),
		)
	}

	if !bytes.Equal(got, expected) {
		// Surface a high-signal reproducer. Pretty-print extensions so
		// the diff is human-readable; print oracle + backend acceptance
		// sets so the divergence step is immediately obvious.
		extBytes, _ := json.MarshalIndent(extensions, "", "  ")
		t.Errorf(
			"property-based byte identity failed\n"+
				"  fixture:         %s\n"+
				"  seed:            %d\n"+
				"  oracle accepted: %v\n"+
				"  backend accepted:%v\n"+
				"  oracle bytes:    %s\n"+
				"  backend bytes:   %s\n"+
				"  extensions:\n%s",
			t.Name(), seed, oracleAccepted, backendAccepted,
			string(expected), string(got), string(extBytes),
		)
	}
}
