// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cyoda/cyoda-cloud-api.proto

package cyoda

import (
	cloudevents "github.com/cyoda-platform/cyoda-go/api/grpc/cloudevents"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_cyoda_cyoda_cloud_api_proto protoreflect.FileDescriptor

const file_cyoda_cyoda_cloud_api_proto_rawDesc = "" +
	"\n" +
	"\x1bcyoda/cyoda-cloud-api.proto\x12\x18org.cyoda.cloud.api.grpc\x1a\x1dcloudevents/cloudevents.proto2\x8b\x04\n" +
	"\x12CloudEventsService\x12R\n" +
	"\x0estartStreaming\x12\x1d.io.cloudevents.v1.CloudEvent\x1a\x1d.io.cloudevents.v1.CloudEvent(\x010\x01\x12Q\n" +
	"\x11entityModelManage\x12\x1d.io.cloudevents.v1.CloudEvent\x1a\x1d.io.cloudevents.v1.CloudEvent\x12L\n" +
	"\fentityManage\x12\x1d.io.cloudevents.v1.CloudEvent\x1a\x1d.io.cloudevents.v1.CloudEvent\x12X\n" +
	"\x16entityManageCollection\x12\x1d.io.cloudevents.v1.CloudEvent\x1a\x1d.io.cloudevents.v1.CloudEvent0\x01\x12L\n" +
	"\fentitySearch\x12\x1d.io.cloudevents.v1.CloudEvent\x1a\x1d.io.cloudevents.v1.CloudEvent\x12X\n" +
	"\x16entitySearchCollection\x12\x1d.io.cloudevents.v1.CloudEvent\x1a\x1d.io.cloudevents.v1.CloudEvent0\x01B3Z1github.com/cyoda-platform/cyoda-go/api/grpc/cyodab\x06proto3"

var file_cyoda_cyoda_cloud_api_proto_goTypes = []any{
	(*cloudevents.CloudEvent)(nil), // 0: io.cloudevents.v1.CloudEvent
}
var file_cyoda_cyoda_cloud_api_proto_depIdxs = []int32{
	0, // 0: org.cyoda.cloud.api.grpc.CloudEventsService.startStreaming:input_type -> io.cloudevents.v1.CloudEvent
	0, // 1: org.cyoda.cloud.api.grpc.CloudEventsService.entityModelManage:input_type -> io.cloudevents.v1.CloudEvent
	0, // 2: org.cyoda.cloud.api.grpc.CloudEventsService.entityManage:input_type -> io.cloudevents.v1.CloudEvent
	0, // 3: org.cyoda.cloud.api.grpc.CloudEventsService.entityManageCollection:input_type -> io.cloudevents.v1.CloudEvent
	0, // 4: org.cyoda.cloud.api.grpc.CloudEventsService.entitySearch:input_type -> io.cloudevents.v1.CloudEvent
	0, // 5: org.cyoda.cloud.api.grpc.CloudEventsService.entitySearchCollection:input_type -> io.cloudevents.v1.CloudEvent
	0, // 6: org.cyoda.cloud.api.grpc.CloudEventsService.startStreaming:output_type -> io.cloudevents.v1.CloudEvent
	0, // 7: org.cyoda.cloud.api.grpc.CloudEventsService.entityModelManage:output_type -> io.cloudevents.v1.CloudEvent
	0, // 8: org.cyoda.cloud.api.grpc.CloudEventsService.entityManage:output_type -> io.cloudevents.v1.CloudEvent
	0, // 9: org.cyoda.cloud.api.grpc.CloudEventsService.entityManageCollection:output_type -> io.cloudevents.v1.CloudEvent
	0, // 10: org.cyoda.cloud.api.grpc.CloudEventsService.entitySearch:output_type -> io.cloudevents.v1.CloudEvent
	0, // 11: org.cyoda.cloud.api.grpc.CloudEventsService.entitySearchCollection:output_type -> io.cloudevents.v1.CloudEvent
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cyoda_cyoda_cloud_api_proto_init() }
func file_cyoda_cyoda_cloud_api_proto_init() {
	if File_cyoda_cyoda_cloud_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cyoda_cyoda_cloud_api_proto_rawDesc), len(file_cyoda_cyoda_cloud_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cyoda_cyoda_cloud_api_proto_goTypes,
		DependencyIndexes: file_cyoda_cyoda_cloud_api_proto_depIdxs,
	}.Build()
	File_cyoda_cyoda_cloud_api_proto = out.File
	file_cyoda_cyoda_cloud_api_proto_goTypes = nil
	file_cyoda_cyoda_cloud_api_proto_depIdxs = nil
}
