// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: cyoda/cyoda-cloud-api.proto

package cyoda

import (
	context "context"
	cloudevents "github.com/cyoda-platform/cyoda-go/api/grpc/cloudevents"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CloudEventsService_StartStreaming_FullMethodName         = "/org.cyoda.cloud.api.grpc.CloudEventsService/startStreaming"
	CloudEventsService_EntityModelManage_FullMethodName      = "/org.cyoda.cloud.api.grpc.CloudEventsService/entityModelManage"
	CloudEventsService_EntityManage_FullMethodName           = "/org.cyoda.cloud.api.grpc.CloudEventsService/entityManage"
	CloudEventsService_EntityManageCollection_FullMethodName = "/org.cyoda.cloud.api.grpc.CloudEventsService/entityManageCollection"
	CloudEventsService_EntitySearch_FullMethodName           = "/org.cyoda.cloud.api.grpc.CloudEventsService/entitySearch"
	CloudEventsService_EntitySearchCollection_FullMethodName = "/org.cyoda.cloud.api.grpc.CloudEventsService/entitySearchCollection"
)

// CloudEventsServiceClient is the client API for CloudEventsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CloudEventsServiceClient interface {
	StartStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[cloudevents.CloudEvent, cloudevents.CloudEvent], error)
	EntityModelManage(ctx context.Context, in *cloudevents.CloudEvent, opts ...grpc.CallOption) (*cloudevents.CloudEvent, error)
	EntityManage(ctx context.Context, in *cloudevents.CloudEvent, opts ...grpc.CallOption) (*cloudevents.CloudEvent, error)
	EntityManageCollection(ctx context.Context, in *cloudevents.CloudEvent, opts ...grpc.CallOption) (grpc.ServerStreamingClient[cloudevents.CloudEvent], error)
	EntitySearch(ctx context.Context, in *cloudevents.CloudEvent, opts ...grpc.CallOption) (*cloudevents.CloudEvent, error)
	EntitySearchCollection(ctx context.Context, in *cloudevents.CloudEvent, opts ...grpc.CallOption) (grpc.ServerStreamingClient[cloudevents.CloudEvent], error)
}

type cloudEventsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudEventsServiceClient(cc grpc.ClientConnInterface) CloudEventsServiceClient {
	return &cloudEventsServiceClient{cc}
}

func (c *cloudEventsServiceClient) StartStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[cloudevents.CloudEvent, cloudevents.CloudEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CloudEventsService_ServiceDesc.Streams[0], CloudEventsService_StartStreaming_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[cloudevents.CloudEvent, cloudevents.CloudEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CloudEventsService_StartStreamingClient = grpc.BidiStreamingClient[cloudevents.CloudEvent, cloudevents.CloudEvent]

func (c *cloudEventsServiceClient) EntityModelManage(ctx context.Context, in *cloudevents.CloudEvent, opts ...grpc.CallOption) (*cloudevents.CloudEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cloudevents.CloudEvent)
	err := c.cc.Invoke(ctx, CloudEventsService_EntityModelManage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudEventsServiceClient) EntityManage(ctx context.Context, in *cloudevents.CloudEvent, opts ...grpc.CallOption) (*cloudevents.CloudEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cloudevents.CloudEvent)
	err := c.cc.Invoke(ctx, CloudEventsService_EntityManage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudEventsServiceClient) EntityManageCollection(ctx context.Context, in *cloudevents.CloudEvent, opts ...grpc.CallOption) (grpc.ServerStreamingClient[cloudevents.CloudEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CloudEventsService_ServiceDesc.Streams[1], CloudEventsService_EntityManageCollection_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[cloudevents.CloudEvent, cloudevents.CloudEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CloudEventsService_EntityManageCollectionClient = grpc.ServerStreamingClient[cloudevents.CloudEvent]

func (c *cloudEventsServiceClient) EntitySearch(ctx context.Context, in *cloudevents.CloudEvent, opts ...grpc.CallOption) (*cloudevents.CloudEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(cloudevents.CloudEvent)
	err := c.cc.Invoke(ctx, CloudEventsService_EntitySearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudEventsServiceClient) EntitySearchCollection(ctx context.Context, in *cloudevents.CloudEvent, opts ...grpc.CallOption) (grpc.ServerStreamingClient[cloudevents.CloudEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CloudEventsService_ServiceDesc.Streams[2], CloudEventsService_EntitySearchCollection_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[cloudevents.CloudEvent, cloudevents.CloudEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CloudEventsService_EntitySearchCollectionClient = grpc.ServerStreamingClient[cloudevents.CloudEvent]

// CloudEventsServiceServer is the server API for CloudEventsService service.
// All implementations must embed UnimplementedCloudEventsServiceServer
// for forward compatibility.
type CloudEventsServiceServer interface {
	StartStreaming(grpc.BidiStreamingServer[cloudevents.CloudEvent, cloudevents.CloudEvent]) error
	EntityModelManage(context.Context, *cloudevents.CloudEvent) (*cloudevents.CloudEvent, error)
	EntityManage(context.Context, *cloudevents.CloudEvent) (*cloudevents.CloudEvent, error)
	EntityManageCollection(*cloudevents.CloudEvent, grpc.ServerStreamingServer[cloudevents.CloudEvent]) error
	EntitySearch(context.Context, *cloudevents.CloudEvent) (*cloudevents.CloudEvent, error)
	EntitySearchCollection(*cloudevents.CloudEvent, grpc.ServerStreamingServer[cloudevents.CloudEvent]) error
	mustEmbedUnimplementedCloudEventsServiceServer()
}

// UnimplementedCloudEventsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCloudEventsServiceServer struct{}

func (UnimplementedCloudEventsServiceServer) StartStreaming(grpc.BidiStreamingServer[cloudevents.CloudEvent, cloudevents.CloudEvent]) error {
	return status.Error(codes.Unimplemented, "method StartStreaming not implemented")
}
func (UnimplementedCloudEventsServiceServer) EntityModelManage(context.Context, *cloudevents.CloudEvent) (*cloudevents.CloudEvent, error) {
	return nil, status.Error(codes.Unimplemented, "method EntityModelManage not implemented")
}
func (UnimplementedCloudEventsServiceServer) EntityManage(context.Context, *cloudevents.CloudEvent) (*cloudevents.CloudEvent, error) {
	return nil, status.Error(codes.Unimplemented, "method EntityManage not implemented")
}
func (UnimplementedCloudEventsServiceServer) EntityManageCollection(*cloudevents.CloudEvent, grpc.ServerStreamingServer[cloudevents.CloudEvent]) error {
	return status.Error(codes.Unimplemented, "method EntityManageCollection not implemented")
}
func (UnimplementedCloudEventsServiceServer) EntitySearch(context.Context, *cloudevents.CloudEvent) (*cloudevents.CloudEvent, error) {
	return nil, status.Error(codes.Unimplemented, "method EntitySearch not implemented")
}
func (UnimplementedCloudEventsServiceServer) EntitySearchCollection(*cloudevents.CloudEvent, grpc.ServerStreamingServer[cloudevents.CloudEvent]) error {
	return status.Error(codes.Unimplemented, "method EntitySearchCollection not implemented")
}
func (UnimplementedCloudEventsServiceServer) mustEmbedUnimplementedCloudEventsServiceServer() {}
func (UnimplementedCloudEventsServiceServer) testEmbeddedByValue()                            {}

// UnsafeCloudEventsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudEventsServiceServer will
// result in compilation errors.
type UnsafeCloudEventsServiceServer interface {
	mustEmbedUnimplementedCloudEventsServiceServer()
}

func RegisterCloudEventsServiceServer(s grpc.ServiceRegistrar, srv CloudEventsServiceServer) {
	// If the following call panics, it indicates UnimplementedCloudEventsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CloudEventsService_ServiceDesc, srv)
}

func _CloudEventsService_StartStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CloudEventsServiceServer).StartStreaming(&grpc.GenericServerStream[cloudevents.CloudEvent, cloudevents.CloudEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CloudEventsService_StartStreamingServer = grpc.BidiStreamingServer[cloudevents.CloudEvent, cloudevents.CloudEvent]

func _CloudEventsService_EntityModelManage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cloudevents.CloudEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudEventsServiceServer).EntityModelManage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudEventsService_EntityModelManage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudEventsServiceServer).EntityModelManage(ctx, req.(*cloudevents.CloudEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudEventsService_EntityManage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cloudevents.CloudEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudEventsServiceServer).EntityManage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudEventsService_EntityManage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudEventsServiceServer).EntityManage(ctx, req.(*cloudevents.CloudEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudEventsService_EntityManageCollection_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(cloudevents.CloudEvent)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CloudEventsServiceServer).EntityManageCollection(m, &grpc.GenericServerStream[cloudevents.CloudEvent, cloudevents.CloudEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CloudEventsService_EntityManageCollectionServer = grpc.ServerStreamingServer[cloudevents.CloudEvent]

func _CloudEventsService_EntitySearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cloudevents.CloudEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudEventsServiceServer).EntitySearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudEventsService_EntitySearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudEventsServiceServer).EntitySearch(ctx, req.(*cloudevents.CloudEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudEventsService_EntitySearchCollection_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(cloudevents.CloudEvent)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CloudEventsServiceServer).EntitySearchCollection(m, &grpc.GenericServerStream[cloudevents.CloudEvent, cloudevents.CloudEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CloudEventsService_EntitySearchCollectionServer = grpc.ServerStreamingServer[cloudevents.CloudEvent]

// CloudEventsService_ServiceDesc is the grpc.ServiceDesc for CloudEventsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudEventsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org.cyoda.cloud.api.grpc.CloudEventsService",
	HandlerType: (*CloudEventsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "entityModelManage",
			Handler:    _CloudEventsService_EntityModelManage_Handler,
		},
		{
			MethodName: "entityManage",
			Handler:    _CloudEventsService_EntityManage_Handler,
		},
		{
			MethodName: "entitySearch",
			Handler:    _CloudEventsService_EntitySearch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "startStreaming",
			Handler:       _CloudEventsService_StartStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "entityManageCollection",
			Handler:       _CloudEventsService_EntityManageCollection_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "entitySearchCollection",
			Handler:       _CloudEventsService_EntitySearchCollection_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cyoda/cyoda-cloud-api.proto",
}
