apiVersion: v1
kind: Service
metadata:
  name: {{ include "cyoda.fullname" . }}
  labels:
    {{- include "cyoda.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "cyoda.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9090
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: 9091
      targetPort: metrics
      protocol: TCP
